### ISSUE TITLE
Setup flask

### ISSUE THREAD

**Issue by devrisby** [devrisby/Habit-Tracker-Fullstack#1]
Goal:
- Confirm application is working

Tasks:
- Create `/api/health` route 
- Test health check route to confirm application runs successfully

Steps:
- Create .gitignore:
- Create virtual environment: `python3 -m venv venv`
- Activate virtual environment: 
  - Linux: `source venv/bin/activate`
  - VsCode: Command Palette > Python: Select Interpreter >  `./venv/bin/python`
- Install packages
  - `pip install flask==2.2.3`
  - `pip install flask-restx=1.1.0`
- Create files
  - Create `src/__init__.py`, `src/app.py`, and `main.py`
- Run app: `python main.py run --debug`

Demo:
![image](https://user-images.githubusercontent.com/118779687/229682757-277e4d15-e168-44bc-988c-24bec849ad44.png)

**Comment by one-numan1** [comment]
Hey @devrisby Please Elaborate your **USE-CASE** and Requirement ? , So I'll Write a scalable API

**Comment by one-numan1** [comment]
I See your Project , It's Simple and Nice. 
Can I contribute  with you in this project.
https://github.com/users/devrisby/projects/

**Comment by devrisby** [comment]
> I See your Project , It's Simple and Nice. Can I contribute with you in this project. https://github.com/users/devrisby/projects/

Thanks for reaching out. This is mainly a personal project for learning flask and full stack web development. 

However if you are interested, I am open to do doing a collaborative, group project. Feel free to reach out at me (riz#8418) in my discord server: https://discord.gg/eDTSTDK8
